services:  
  sqlserver-windows:
    image: acrsabentisimages.azurecr.io/windowscontainers/sqlserver2022base:v1.0.5
    container_name: sql_server-windows
    environment:
      - MSSQL_ADMIN_USERNAME=sa
      - MSSQL_ADMIN_PWD=admin
      - MSSQL_PATH_DATA=d:\data
      - MSSQL_PATH_LOG=d:\logs
      - MSSQL_PATH_BACKUP=d:\backup
      - MSSQL_PATH_SYSTEM=d:\system
    volumes:
      - d:/backup:d:/
    networks:
      mynetwork:
        ipv4_address: 192.168.1.5
networks:
  mynetwork:
   external: true