version: '3.8'

services:
  sqlserver:
    build: .
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "!root2024"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - sqlservernetwork

volumes:
  sqlserverdata:

networks:
  sqlservernetwork:
    driver: bridge
